name: Email Automation Scheduler

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-email-agent:
    runs-on: ubuntu-latest
    timeout-minutes: 45 # Increased timeout for larger model download/setup

    env:
      # --- General Email Secrets ---
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      IMAP_SERVER: imap.gmail.com
      SMTP_SERVER: smtp.gmail.com
      PYTHONUNBUFFERED: 1
      
      # --- For AirLLM to cache models ---
      HF_HOME: /home/runner/.cache/huggingface
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Cache Hugging Face models
        uses: actions/cache@v3
        with:
          path: ${{ env.HF_HOME }}
          key: ${{ runner.os }}-huggingface-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-huggingface-

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          # AirLLM requires PyTorch with CUDA support, transformers, and other dependencies
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
          pip install airllm transformers sentencepiece accelerate

      - name: Run Email Agent with AirLLM
        run: |
          echo "Starting Email Automation with AirLLM..."
          python email_agent.py
