name: Email Automation Scheduler

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-email-agent:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    services:
      ollama_service:
        image: ollama/ollama:latest
        ports:
          - 11434:11434
        env:
          OLLAMA_NUM_THREAD: "0"
        options: >-
          --name ollama_service
          --health-cmd="ollama -v"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      IMAP_SERVER: imap.gmail.com
      SMTP_SERVER: smtp.gmail.com
      OLLAMA_URL: http://localhost:11434/api/generate
      OLLAMA_MODEL: mistral:4b-instruct-q4_0
      LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install requests

      - name: Wait for Ollama Service
        run: |
          echo "Waiting for Ollama service health..."
          for i in {1..24}; do
            if docker inspect --format='{{json .State.Health.Status}}' ollama_service | grep -q healthy; then
              echo "Ollama service is healthy!"
              break
            else
              echo "Still waiting for Ollama... ($i/24)"
              sleep 5
            fi
            if [ $i -eq 24 ]; then
              echo "Ollama service failed to become healthy. Aborting."
              exit 1
            fi
          done

      - name: Pull Mistral 4B Instruct Model
        run: |
          echo "Pulling model ${{ env.OLLAMA_MODEL }}..."
          docker exec ollama_service ollama pull ${{ env.OLLAMA_MODEL }}

      - name: Warm-up Ollama Model
        run: |
          curl http://localhost:11434/api/generate -d '{
            "model": "${{ env.OLLAMA_MODEL }}",
            "prompt": "Hi",
            "stream": false,
            "options": {"num_predict": 1}
          }' --max-time 120

      - name: Run Email Agent
        run: |
          echo "Starting Email Automation..."
          python email_agent.py
