name: Email Automation Scheduler

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-email-agent:
    runs-on: ubuntu-latest

    services:
      ollama_service:
        image: ollama/ollama:latest
        ports:
          - 11434:11434
        # ✅ Final fix with quotes
        options: '--name ollama_service --health-cmd="ollama -v" --health-interval=10s --health-timeout=5s --health-retries=5'

    env:
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
      LLM_MODEL: mistral:instruct
      OLLAMA_MODEL: mistral:instruct
      IMAP_SERVER: imap.gmail.com
      SMTP_SERVER: smtp.gmail.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache Ollama models
        uses: actions/cache@v4
        with:
          path: ~/.ollama/models
          key: ollama-models-${{ env.LLM_MODEL }}

      - name: Install dependencies
        run: |
          pip install requests imap
