name: Email Automation Scheduler

on:
  schedule:
    # Runs every 15 minutes to allow time for installation
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-email-agent:
    runs-on: ubuntu-latest
    timeout-minutes: 45 # Generous timeout for a clean installation

    services:
      ollama:
        image: ollama/ollama:latest
        ports:
          - 11434:11434

    env:
      # --- General Email Secrets ---
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      IMAP_SERVER: imap.gmail.com
      SMTP_SERVER: smtp.gmail.com
      PYTHONUNBUFFERED: 1

      # --- Ollama Configuration ---
      OLLAMA_URL: http://localhost:11434/api/generate
      LLM_MODEL: mistral:7b-instruct-q4_0

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Wait for Ollama service to be ready
        run: |
          echo "Waiting for Ollama service..."
          until curl -s http://localhost:11434; do
            echo -n .
            sleep 1
          done
          echo "Ollama service is up."

      - name: Pull Ollama Model
        run: |
          echo "Pulling Ollama model: ${{ env.LLM_MODEL }}"
          curl -s http://localhost:11434/api/pull -d '{"name": "${{ env.LLM_MODEL }}"}'
          echo "Model pull complete."

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install requests

      - name: Run Email Agent
        run: |
          echo "Starting Email Automation with Ollama..."
          python email_agent.py
