name: Email Automation Scheduler

on:
  schedule:
    # Run every 15 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-email-agent:
    runs-on: ubuntu-latest

    services:
      # Define the Ollama service
      ollama_service:
        image: ollama/ollama:latest
        ports:
          - 11434:11434
        # Healthcheck to ensure Ollama is ready before running the job steps
        options: >-
          --name ollama_service
          --health-cmd="ollama -v"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      # Email Credentials (MUST be set in your Repository Secrets)
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      # Ollama Configuration
      IMAP_SERVER: imap.gmail.com
      SMTP_SERVER: smtp.gmail.com
      OLLAMA_URL: http://ollama_service:11434/api/generate
      OLLAMA_MODEL: mistral:instruct-q4
      # LangSmith (Optional, but useful for tracing)
      LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }} 
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install requests

      # Step 1: Wait for the Ollama service to start and become healthy
      - name: Wait for Ollama Service
        id: wait_ollama
        run: |
          echo "Waiting up to 2 minutes for Ollama service health..."
          for i in {1..24}; do
            # Check the Docker health status
            if docker inspect --format='{{json .State.Health.Status}}' ollama_service | grep -q healthy; then
              echo "Ollama service is healthy!"
              break
            else
              echo "Still waiting for Ollama... ($i/24)"
              sleep 5
            fi
            if [ $i -eq 24 ]; then
              echo "Ollama service failed to become healthy. Aborting."
              exit 1
            fi
          done

      # Step 2: Pull the Mistral model (lightweight and fast)
      - name: Pull Mistral Model
        id: pull_model
        run: |
          echo "Pulling lightweight Mistral model (${{ env.OLLAMA_MODEL }})..."
          # This command executes inside the running ollama_service container
          # Added a retry mechanism in case of temporary network issues
          docker exec ollama_service ollama pull ${{ env.OLLAMA_MODEL }} || {
            echo "Retrying model pull after 10 seconds..."
            sleep 10
            docker exec ollama_service ollama pull ${{ env.OLLAMA_MODEL }}
          }

      # Step 3: Run the Python Email Agent
      - name: Run Email Agent
        id: run_agent
        run: |
          echo "Starting Email Automation..."
          python email_agent.py
