name: Email Automation Scheduler

on:
  schedule:
    # Runs every 15 minutes to allow more time for the larger model setup
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-email-agent:
    runs-on: ubuntu-latest
    timeout-minutes: 45 # Increased timeout for model download and setup

    env:
      # --- General Email Secrets ---
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      IMAP_SERVER: imap.gmail.com
      SMTP_SERVER: smtp.gmail.com
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          # Disable the default pip cache to ensure a clean install
          cache: 'pip'
          cache-dependency-path: '**/non-existent-file' # Invalid path to force a cache miss

      - name: Force Clean Install of Dependencies
        run: |
          pip install --upgrade pip
          # Install each package individually and force no-cache to prevent issues
          pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install --no-cache-dir transformers==4.48.0
          pip install --no-cache-dir optimum
          pip install --no-cache-dir airllm sentencepiece accelerate

      - name: Verify Installation
        run: |
          echo "--- Verifying installed packages ---"
          pip list
          echo "------------------------------------"
          echo "Checking for 'optimum' package..."
          pip show optimum
          echo "------------------------------------"
          echo "Checking for 'transformers' package..."
          pip show transformers
          echo "------------------------------------"

      - name: Run Email Agent with AirLLM
        run: |
          echo "Starting Email Automation with AirLLM..."
          python email_agent.py
