name: Email Automation Scheduler

on:
  schedule:
    # Run every 15 minutes (adjust if needed)
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-email-agent:
    runs-on: ubuntu-latest

    services:
      ollama_service:
        image: ollama/ollama:latest
        ports:
          - 11434:11434
        # ✅ FIXED: Proper single-line docker healthcheck syntax (no newline issue)
        options: >-
          --name ollama_service
          --health-cmd="ollama -v"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      IMAP_SERVER: imap.gmail.com
      SMTP_SERVER: smtp.gmail.com
      OLLAMA_URL: http://ollama_service:11434/api/generate
      OLLAMA_MODEL: mistral:instruct-q4
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install requests imapclient

      # ✅ Wait for the Ollama service to start and become healthy
      - name: Wait for Ollama Service
        run: |
          echo "Waiting up to 2 minutes for Ollama service health..."
          for i in {1..24}; do
            if docker inspect --format='{{json .State.Health.Status}}' ollama_service | grep -q healthy; then
              echo "Ollama service is healthy!"
              break
            else
              echo "Still waiting for Ollama... ($i/24)"
              sleep 5
            fi
          done

      # ✅ Pull the Mistral model (smaller & faster)
      - name: Pull Mistral Model
        run: |
          echo "Pulling lightweight Mistral model..."
          docker exec ollama_service ollama pull mistral:instruct-q4 || {
            echo "Retrying model pull..."
            sleep 10
            docker exec ollama_service ollama pull mistral:instruct-q4
          }

      - name: Run Email Agent
        run: |
          echo "Starting Email Automation..."
          python email_agent.py
