name: Email Automation Scheduler

# This sets the trigger to run the workflow automatically every 5 minutes
on:
  schedule:
    - cron: '* * * * *'   # Every 1 minutes
 

jobs:
  run-email-agent:
    runs-on: ubuntu-latest

    env:
      TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Email Agent
        run: python email_agent.py
