name: Email Automation Scheduler

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-email-agent:
    runs-on: ubuntu-latest

    services:
      ollama_service:
        image: ollama/ollama:latest
        ports:
          - 11434:11434
        options: >
          --name ollama_service
          --health-cmd "ollama -v"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      LLM_MODEL: mistral:instruct
      OLLAMA_MODEL: mistral:instruct
      LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache Ollama models
        uses: actions/cache@v4
        with:
          path: ~/.ollama/models
          key: ollama-models-${{ env.LLM_MODEL }}

      - name: Install dependencies
        run: pip install requests imapclient

      - name: Preload model
        run: |
          docker exec ollama_service ollama pull ${LLM_MODEL}
          docker exec ollama_service ollama run ${LLM_MODEL} --prompt "Ready"

      - name: Run Email Agent
        run: python email_agent.py
